### PR TITLE
#165 damage pop animation

### LINKED ISSUE #165: [UI] Damage "Pop" animation
**How will this enhancement improve the game?**
When a player kills a titan, the damage is instantly displayed on the screen. Within AoTTG, an effect would be played where the damage would "pop" into the screen, by making use of scaling. Goes from small to big, and big to small after x seconds.

**Describe the solution you'd like**
It is required that this animation is brought back to AoTTG2 due to its iconic nature.

### PR DESCRIPTION
**Pull request by Zoap**
Popup animation added for damage indication in player HUD. Animation might need additional tweeking since i'm not an animator, but now at least the feature is implemented.

### CODE REVIEW

**Comment by Zoap** [comment]
Art Team is tweaking the animation of the popup as I write this comment

**Review by Lithrun — APPROVED** [review]
Nothing really changed to the code, so all good there 👍 
Resolve the merge conflict, create the builds and then give testing team a day or two to check this (just animation so should be done fairly quickly.)

**Comment by sonicv6** [comment]
This PR should be ready

**Review by Lithrun — CHANGES_REQUESTED** [review]
PR states that there are 1230 files changed. That seems like a lot to fix a damage pop animation. Investigation required.

**Comment by sonicv6** [comment]
image
Just something weird about the PR. Gonna reopen it

**Pull request closed without merging**
