### PR TITLE
#205 hook sound distortion

### PR DESCRIPTION
**Pull request by nolanrdavenport**

### CODE REVIEW

**Comment by nolanrdavenport** [comment]
SonarCloud failed due to TODO for adding an empty tank sound.

**Comment by Lithrun** [comment]
Probably in terms of functionality this seems fine, although will have to be place it on hold for ~1 week as then the changes of HERO can be merged into development beforehand, as this PR might cause merge conflicts.

**Comment by nolanrdavenport** [comment]
@Lithrun I believe Toorah merged this into the branch where he is doing the refactoring. Idk for sure, but this pull request might be redundant. Should I close?

**Comment by Lithrun** [comment]
> 
> 
> @Lithrun I believe Toorah merged this into the branch where he is doing the refactoring. Idk for sure, but this pull request might be redundant. Should I close?

Will see next week, as #33 has been merged into development, and testing time will check if any existing bugs still occur or not

**Pull request closed without merging**
