### PR TITLE
#33 toorah 3times the charm

### PR DESCRIPTION
**Pull request by Toorah**

### CODE REVIEW

**Review by Lithrun — CHANGES_REQUESTED** [review]
So far I've noticed:
- [x] Using a Hero Skill, actives the bomb mode skill
- [x] IPhotonService is missing in the ServiceManager.prefab
- [x] Radial flare menu is missing
~~- [ ] Players appear to (partially) go inside a titan when titans use their attacks~~ This also occurs on `development`
- [x] Player does not go into the titans hand when they are grabbed, yet they will still die if the titan finishes the eat animation. Trying to save yourself from being grabbed in this state, causes a null reference in Hero.Ungrabbed
- [x] Quitting a room, and then joining a new one causes a null reference on Hero.Equipment and HookUI
- [x] Character death is not implemented yet. Ideally this would be the character bodypart split up, but for now this will be moved into a new issue. The "explosion" death will be used for now
- [x] Rebinds menu cannot be closed
- [x] Graphics Menu returns a null reference
- [x] When you look at a 30-45 degree angle up, your character will stand while sliding, instead of playing the sliding animation
- [x] After using a double gas burst, the player will enter the stand animation mid air

Will try to resolve some of these, and mark those that are done.

**Comment by Lithrun** [comment]
https://github.com/AoTTG-2/AoTTG-2/pull/589#pullrequestreview-610603826

Alright, so all of above is resolved. Now the time to review the code.

**Review by Lithrun — APPROVED** [review]
For over a year this issue has been there, and now it can finally be closed. Whereas it ain't perfect, it's good enough for now. Time to work on those issues that were blocked now~

**Comment by gisketch** [comment]
> For over a year this issue has been there, and now it can finally be closed. Whereas it ain't perfect, it's good enough for now. Time to work on those issues that were blocked now~

This calls for celebration! Hooray!

**Comment by KoroSensei0320** [comment]
:koro:

**Pull request merged**
