### PR TITLE
#508 Namespace on levelbuilder and block PTs on certain maps

### PR DESCRIPTION
**Pull request by merinobruno**
LevelBuilder now has namespace.
Needed to import Levelbuilder route to a few files:
-ServerSettingsPage.cs
-CreateRoom.cs
-SinglePlayer.cs

Player Titans now are unable to spawn in:
-Akina
-Cave Fight
-House Fight

### CODE REVIEW

**Comment by merinobruno** [comment]
I found another bug trying to fix this one.
When I start the game, the IsPlayerTitanEnabled variable remains true or false in the entire game depending on which map I select first.
Example: If I start the game and start a Cave Fight game, the option for being a PT will remain hidden on all the other maps. and viceversa.
I'm trying to fix this one too.

**Comment by Lithrun** [comment]
> 
> 
> I found another bug trying to fix this one.
> When I start the game, the IsPlayerTitanEnabled variable remains true or false in the entire game depending on which map I select first.
> Example: If I start the game and start a Cave Fight game, the option for being a PT will remain hidden on all the other maps. and viceversa.
> I'm trying to fix this one too.

Nice find 👍

**Review by Lithrun — APPROVED** [review]
Easy fix, although for your next PR, please don't include useless comments.

**Comment by Lithrun** [comment]
Not too sure why the CI fails. Maybe re-opening a new PR fixes it

**Pull request closed without merging**
